import { BIOME_CENTERS } from '../data/world.ts';

// Gameplay tuning belongs here; map geometry and item values live in src/data.
export const RULES = {
  defaultSeed: 73_021,
  spawnX: BIOME_CENTERS.meadow[0],
  starterNodeOffsets: [
    ['wood', -75],
    ['stone', 70],
    ['fiber', -145],
    ['flint', 140],
    ['water', 210],
    ['berry', -20],
  ] as [string, number][],
  maxVital: 100,
  playerHalfWidth: 13,
  playerHeight: 47,
  playerFootInset: 2,
  jumpVelocity: 340,
  jumpStamina: 4,
  mineReach: 96,
  mineStamina: 8,
  staleAtFraction: 0.22,
  placeReach: 170,
  placeEdgePadding: 35,
  structureSpacing: 54,
  platformSpacing: 24,
  interactReach: 78,
  gatherReach: 84,
  fishReach: 98,
  fishSuccessChance: 0.67,
  cropGrowthSeconds: 240,
  campfireInitialFuel: 420,
  campfireRefuel: 360,
  iceboxRefuel: 900,
  lanternRefuel: 800,
  washHygieneGain: 36,
  minutesAtStart: 8 * 60,
  minutesPerSecond: 1.2,
  minutesPerDay: 24 * 60,
  nightEndsAt: 6 * 60,
  nightStartsAt: 19 * 60,
  standardMoveSpeed: 180,
  tiredMoveSpeed: 95,
  gravity: 850,
  terminalVelocity: 550,
  climbVelocity: 155,
  fallDamageVelocity: 470,
  attackStamina: 11,
  attackCooldownSeconds: 0.52,
  bossWeaponTier: 5,
  weatherBaseSeconds: 120,
  weatherJitterSeconds: 130,
  rainCatchRate: 0.035,
  rainCatchCapacity: 8,
  worldGenerationAttemptsPerNode: 35,
  resourceSpread: 1120,
  animalSpread: 870,
  resourceWorldPadding: 65,
  animalWorldPadding: 70,
  entranceResourceClearance: 80,
  maxTickSeconds: 0.1,
  maxOfflineSeconds: 24 * 60 * 60,
  cooledSpoilageRate: 0.18,
  saveKey: 'wildlands-save-v1',
} as const;
